### ISSUE TITLE
in "project"，i can find autogeneration  java-gen   ...but at "Android ",i can not find autogeneration  java-gen**

### ISSUE THREAD

**Issue by ayyb1988** [SureCase/GreenDaoForAndroidStudio#4]
## **in "project"，i can find autogeneration  java-gen**

![image](https://cloud.githubusercontent.com/assets/7148115/6161529/15e3b22c-b2ad-11e4-91c8-fa5e91dfb041.png)
## **but at "Android ",i can not find autogeneration  java-gen**

![image](https://cloud.githubusercontent.com/assets/7148115/6161511/ede0a154-b2ac-11e4-8347-1bd9e8bb8117.png)
## And In MyApplication ,i can not import autogeneration class .eg DaoMaster

![image](https://cloud.githubusercontent.com/assets/7148115/6161572/c708b980-b2ad-11e4-8750-19561beab2ab.png)

**Comment by Aspsine** [comment]
sourceSets {
        main {
            manifest.srcFile 'src/main/AndroidManifest.xml'
            java.srcDirs = ['src/main/java', 'src/main/java-gen']
            res.srcDirs = ['src/main/res']
        }
    }

**Comment by ayyb1988** [comment]
## sorry,this is my problem.  "main" error write "mian" .fuck

**src/main/java', 'src/mian/java-gen'         main  mian**

**Comment by ayyb1988** [comment]
@Aspsine thx
